# Generated by Django 4.0.1 on 2022-01-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeFranchise',
            fields=[
                ('fran_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quality_up', models.IntegerField()),
                ('quality_down', models.IntegerField()),
            ],
            options={
                'db_table': 'cafe_franchise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialArea',
            fields=[
                ('comm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comm_id_name', models.CharField(blank=True, max_length=256, null=True)),
                ('comm_category', models.CharField(max_length=256)),
                ('comm_category_name', models.CharField(max_length=256)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'commercial_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('culture_id', models.AutoField(primary_key=True, serialize=False)),
                ('culture_category', models.CharField(blank=True, max_length=256, null=True)),
                ('culture_name', models.CharField(blank=True, max_length=256, null=True)),
                ('culture_addr', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'culture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('gu', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('number_10_19m', models.IntegerField(db_column='10_19m')),
                ('number_10_19w', models.IntegerField(db_column='10_19w')),
                ('number_20_29m', models.IntegerField(db_column='20_29m')),
                ('number_20_29w', models.IntegerField(db_column='20_29w')),
                ('number_30_39m', models.IntegerField(db_column='30_39m')),
                ('number_30_39w', models.IntegerField(db_column='30_39w')),
                ('number_40_49m', models.IntegerField(db_column='40_49m')),
                ('number_40_49w', models.IntegerField(db_column='40_49w')),
                ('number_50_59m', models.IntegerField(db_column='50_59m')),
                ('number_50_59w', models.IntegerField(db_column='50_59w')),
                ('number_60_69m', models.IntegerField(db_column='60_69m')),
                ('number_60_69w', models.IntegerField(db_column='60_69w')),
                ('total_worker', models.IntegerField()),
                ('density', models.IntegerField()),
            ],
            options={
                'db_table': 'population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=256)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('coms', models.IntegerField()),
                ('many75', models.IntegerField()),
                ('trans', models.IntegerField()),
            ],
            options={
                'db_table': 'traffic',
                'managed': False,
            },
        ),
    ]
