# Generated by Django 4.0.1 on 2022-01-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CafeCount',
        ),
        migrations.DeleteModel(
            name='CafeFranchise',
        ),
        migrations.DeleteModel(
            name='CafeStatus',
        ),
        migrations.DeleteModel(
            name='CafeUser',
        ),
        migrations.DeleteModel(
            name='CommercialArea',
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.DeleteModel(
            name='Traffic',
        ),
    ]
